# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'purchase_history.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BMT_client_main_windows(object):
    def setupUi(self, BMT_client_main_windows):
        BMT_client_main_windows.setObjectName("BMT_client_main_windows")
        BMT_client_main_windows.resize(800, 800)
        BMT_client_main_windows.setMaximumSize(QtCore.QSize(800, 800))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        BMT_client_main_windows.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/resource/BMT_64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BMT_client_main_windows.setWindowIcon(icon)
        BMT_client_main_windows.setStyleSheet("background-color: rgb(238, 255, 243);")
        self.centralwidget = QtWidgets.QWidget(BMT_client_main_windows)
        self.centralwidget.setObjectName("centralwidget")
        self.client_name = QtWidgets.QLabel(self.centralwidget)
        self.client_name.setGeometry(QtCore.QRect(60, 10, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Mistral")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.client_name.setFont(font)
        self.client_name.setAlignment(QtCore.Qt.AlignCenter)
        self.client_name.setObjectName("client_name")
        self.client_logo = QtWidgets.QLabel(self.centralwidget)
        self.client_logo.setGeometry(QtCore.QRect(55, 55, 128, 128))
        self.client_logo.setObjectName("client_logo")
        self.output = QtWidgets.QPushButton(self.centralwidget)
        self.output.setGeometry(QtCore.QRect(690, 740, 100, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.output.setFont(font)
        self.output.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.output.setObjectName("output")
        self.client_logo.raise_()
        self.client_name.raise_()
        self.output.raise_()
        BMT_client_main_windows.setCentralWidget(self.centralwidget)

        self.retranslateUi(BMT_client_main_windows)
        QtCore.QMetaObject.connectSlotsByName(BMT_client_main_windows)

    def retranslateUi(self, BMT_client_main_windows):
        _translate = QtCore.QCoreApplication.translate
        BMT_client_main_windows.setWindowTitle(_translate("BMT_client_main_windows", "BMT_client"))
        self.client_name.setText(_translate("BMT_client_main_windows", "<html><head/><body><p><span style=\" font-size:28pt; font-style:italic;\">BMT</span></p></body></html>"))
        self.client_logo.setText(_translate("BMT_client_main_windows", "<html><head/><body><p><img src=\":/logo/resource/BMT_128.ico\"/></p></body></html>"))
        self.output.setText(_translate("BMT_client_main_windows", "导出"))
from client import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BMT_client_main_windows = QtWidgets.QMainWindow()
    ui = Ui_BMT_client_main_windows()
    ui.setupUi(BMT_client_main_windows)
    BMT_client_main_windows.show()
    sys.exit(app.exec_())
