# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_to.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_BMT_client_register_to(object):
    def setupUi(self, BMT_client_register_to):
        BMT_client_register_to.setObjectName("BMT_client_register_to")
        BMT_client_register_to.resize(650, 350)
        BMT_client_register_to.setMaximumSize(QtCore.QSize(650, 350))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/resource/BMT_64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BMT_client_register_to.setWindowIcon(icon)
        BMT_client_register_to.setToolTipDuration(-1)
        BMT_client_register_to.setStyleSheet("background-color: rgb(238, 255, 243);")
        self.centralwidget = QtWidgets.QWidget(BMT_client_register_to)
        self.centralwidget.setObjectName("centralwidget")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(290, 145, 80, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.password = QtWidgets.QLineEdit(self.centralwidget)
        self.password.setGeometry(QtCore.QRect(380, 145, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.password.setFont(font)
        self.password.setMaxLength(15)
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(290, 100, 80, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(290, 190, 80, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.password_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.password_2.setGeometry(QtCore.QRect(380, 190, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.password_2.setFont(font)
        self.password_2.setMaxLength(15)
        self.password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_2.setObjectName("password_2")
        self.register_to = QtWidgets.QPushButton(self.centralwidget)
        self.register_to.setGeometry(QtCore.QRect(390, 260, 75, 23))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.register_to.setFont(font)
        self.register_to.setObjectName("register_to")
        self.account = QtWidgets.QLineEdit(self.centralwidget)
        self.account.setGeometry(QtCore.QRect(380, 100, 200, 30))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(11)
        self.account.setFont(font)
        self.account.setToolTipDuration(-1)
        self.account.setMaxLength(15)
        self.account.setObjectName("account")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(150, 10, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(50, 10, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Mistral")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(30, 30, 256, 256))
        self.label_7.setObjectName("label_7")
        self.call_for_help = QtWidgets.QCommandLinkButton(self.centralwidget)
        self.call_for_help.setGeometry(QtCore.QRect(460, 300, 171, 41))
        self.call_for_help.setToolTipDuration(0)
        self.call_for_help.setObjectName("call_for_help")
        self.log_in = QtWidgets.QPushButton(self.centralwidget)
        self.log_in.setGeometry(QtCore.QRect(480, 20, 150, 23))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.log_in.setFont(font)
        self.log_in.setObjectName("log_in")
        self.back = QtWidgets.QPushButton(self.centralwidget)
        self.back.setGeometry(QtCore.QRect(480, 260, 91, 23))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.back.setFont(font)
        self.back.setObjectName("back")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(580, 150, 51, 20))
        self.checkBox.setObjectName("checkBox")
        self.label_7.raise_()
        self.label_3.raise_()
        self.password.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.password_2.raise_()
        self.register_to.raise_()
        self.account.raise_()
        self.label.raise_()
        self.label_6.raise_()
        self.call_for_help.raise_()
        self.log_in.raise_()
        self.back.raise_()
        self.checkBox.raise_()
        BMT_client_register_to.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(BMT_client_register_to)
        self.statusbar.setObjectName("statusbar")
        BMT_client_register_to.setStatusBar(self.statusbar)

        self.retranslateUi(BMT_client_register_to)
        QtCore.QMetaObject.connectSlotsByName(BMT_client_register_to)
        BMT_client_register_to.setTabOrder(self.account, self.password)
        BMT_client_register_to.setTabOrder(self.password, self.checkBox)
        BMT_client_register_to.setTabOrder(self.checkBox, self.password_2)
        BMT_client_register_to.setTabOrder(self.password_2, self.register_to)
        BMT_client_register_to.setTabOrder(self.register_to, self.call_for_help)
        BMT_client_register_to.setTabOrder(self.call_for_help, self.back)
        BMT_client_register_to.setTabOrder(self.back, self.log_in)

    def retranslateUi(self, BMT_client_register_to):
        _translate = QtCore.QCoreApplication.translate
        BMT_client_register_to.setWindowTitle(_translate("BMT_client_register_to", "BMT_client"))
        self.label_3.setText(_translate("BMT_client_register_to", "密码"))
        self.label_2.setText(_translate("BMT_client_register_to", "账号"))
        self.label_4.setText(_translate("BMT_client_register_to", "确认密码"))
        self.register_to.setText(_translate("BMT_client_register_to", "注册"))
        self.account.setPlaceholderText(_translate("BMT_client_register_to", "请输入账号"))
        self.label.setText(_translate("BMT_client_register_to", "欢迎注册"))
        self.label_6.setText(_translate("BMT_client_register_to", "<html><head/><body><p><span style=\" font-size:28pt; font-style:italic;\">BMT</span></p></body></html>"))
        self.label_7.setText(_translate("BMT_client_register_to", "<html><head/><body><p><img src=\":/logo/resource/BMT.png\"/></p></body></html>"))
        self.call_for_help.setToolTip(_translate("BMT_client_register_to", "<html><head/><body><p><span style=\" font-size:12pt; text-decoration: underline; color:#0000ff;\">huyan35@mail2.sysu.edu.cn</span></p></body></html>"))
        self.call_for_help.setText(_translate("BMT_client_register_to", "联系客服（点我复制）"))
        self.log_in.setText(_translate("BMT_client_register_to", "已有账号？请登录>"))
        self.back.setText(_translate("BMT_client_register_to", "回到主页>"))
        self.checkBox.setText(_translate("BMT_client_register_to", "显示"))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BMT_client_register_to = QtWidgets.QMainWindow()
    ui = Ui_BMT_client_register_to()
    ui.setupUi(BMT_client_register_to)
    BMT_client_register_to.show()
    sys.exit(app.exec_())

