# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'register_success.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_BMT_client_register(object):
    def setupUi(self, BMT_client_register):
        BMT_client_register.setObjectName("BMT_client_register")
        BMT_client_register.resize(650, 300)
        BMT_client_register.setMaximumSize(QtCore.QSize(650, 300))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/resource/BMT_64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BMT_client_register.setWindowIcon(icon)
        BMT_client_register.setStyleSheet("background-color: rgb(238, 255, 243);")
        self.label_6 = QtWidgets.QLabel(BMT_client_register)
        self.label_6.setGeometry(QtCore.QRect(150, 10, 331, 50))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.log_in = QtWidgets.QPushButton(BMT_client_register)
        self.log_in.setGeometry(QtCore.QRect(340, 170, 100, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.log_in.setFont(font)
        self.log_in.setObjectName("log_in")
        self.exit = QtWidgets.QPushButton(BMT_client_register)
        self.exit.setGeometry(QtCore.QRect(460, 170, 100, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.exit.setFont(font)
        self.exit.setObjectName("exit")
        self.label_7 = QtWidgets.QLabel(BMT_client_register)
        self.label_7.setGeometry(QtCore.QRect(50, 10, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Mistral")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(BMT_client_register)
        self.label_8.setGeometry(QtCore.QRect(30, 30, 256, 256))
        self.label_8.setObjectName("label_8")
        self.call_for_help = QtWidgets.QCommandLinkButton(BMT_client_register)
        self.call_for_help.setGeometry(QtCore.QRect(460, 250, 161, 41))
        self.call_for_help.setToolTipDuration(0)
        self.call_for_help.setObjectName("call_for_help")
        self.back = QtWidgets.QPushButton(BMT_client_register)
        self.back.setGeometry(QtCore.QRect(530, 20, 91, 23))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.back.setFont(font)
        self.back.setObjectName("back")
        self.label_8.raise_()
        self.label_6.raise_()
        self.log_in.raise_()
        self.exit.raise_()
        self.label_7.raise_()
        self.call_for_help.raise_()
        self.back.raise_()

        self.retranslateUi(BMT_client_register)
        QtCore.QMetaObject.connectSlotsByName(BMT_client_register)

    def retranslateUi(self, BMT_client_register):
        _translate = QtCore.QCoreApplication.translate
        BMT_client_register.setWindowTitle(_translate("BMT_client_register", "BMT_client"))
        self.label_6.setText(_translate("BMT_client_register", "恭喜您，注册成功！快去登陆吧！"))
        self.log_in.setText(_translate("BMT_client_register", "去登录"))
        self.exit.setText(_translate("BMT_client_register", "取消"))
        self.label_7.setText(_translate("BMT_client_register", "<html><head/><body><p><span style=\" font-size:28pt; font-style:italic;\">BMT</span></p></body></html>"))
        self.label_8.setText(_translate("BMT_client_register", "<html><head/><body><p><img src=\":/logo/resource/BMT.png\"/></p></body></html>"))
        self.call_for_help.setToolTip(_translate("BMT_client_register", "<html><head/><body><p><span style=\" font-size:12pt; text-decoration: underline; color:#0000ff;\">huyan35@mail2.sysu.edu.cn</span></p></body></html>"))
        self.call_for_help.setText(_translate("BMT_client_register", "联系客服（点我复制）"))
        self.back.setText(_translate("BMT_client_register", "回到主页>"))
import resource_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    BMT_client_register = QtWidgets.QWidget()
    ui = Ui_BMT_client_register()
    ui.setupUi(BMT_client_register)
    BMT_client_register.show()
    sys.exit(app.exec_())
