# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shop_pricechange.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_price_change(object):
    def setupUi(self, price_change):
        price_change.setObjectName("price_change")
        price_change.resize(650, 620)
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        price_change.setFont(font)
        price_change.setWindowTitle("更新进价")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/ico/resource/BMT_64.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        price_change.setWindowIcon(icon)
        price_change.setStyleSheet("background-color: rgb(255, 245, 220);")
        self.centralwidget = QtWidgets.QWidget(price_change)
        self.centralwidget.setObjectName("centralwidget")
        self.client_name = QtWidgets.QLabel(self.centralwidget)
        self.client_name.setGeometry(QtCore.QRect(120, 40, 100, 50))
        font = QtGui.QFont()
        font.setFamily("Mistral")
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.client_name.setFont(font)
        self.client_name.setAlignment(QtCore.Qt.AlignCenter)
        self.client_name.setObjectName("client_name")
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setGeometry(QtCore.QRect(410, 480, 100, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.cancel.setFont(font)
        self.cancel.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel.setObjectName("cancel")
        self.confirm = QtWidgets.QPushButton(self.centralwidget)
        self.confirm.setGeometry(QtCore.QRect(250, 480, 140, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.confirm.setFont(font)
        self.confirm.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.confirm.setObjectName("confirm")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 10, 161, 51))
        font = QtGui.QFont()
        font.setFamily("华文楷体")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 280, 111, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(100, 360, 111, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.price_change_input = QtWidgets.QLineEdit(self.centralwidget)
        self.price_change_input.setGeometry(QtCore.QRect(260, 360, 261, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.price_change_input.setFont(font)
        self.price_change_input.setObjectName("price_change_input")
        self.book_name = QtWidgets.QComboBox(self.centralwidget)
        self.book_name.setGeometry(QtCore.QRect(260, 280, 261, 31))
        self.book_name.setObjectName("book_name")
        self.original_price = QtWidgets.QPushButton(self.centralwidget)
        self.original_price.setGeometry(QtCore.QRect(100, 480, 140, 40))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(14)
        self.original_price.setFont(font)
        self.original_price.setObjectName("original_price")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(100, 200, 111, 31))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.book_type = QtWidgets.QComboBox(self.centralwidget)
        self.book_type.setGeometry(QtCore.QRect(260, 200, 261, 31))
        self.book_type.setObjectName("book_type")
        self.client_logo = QtWidgets.QLabel(self.centralwidget)
        self.client_logo.setGeometry(QtCore.QRect(10, 10, 128, 128))
        self.client_logo.setObjectName("client_logo")
        price_change.setCentralWidget(self.centralwidget)

        self.retranslateUi(price_change)
        QtCore.QMetaObject.connectSlotsByName(price_change)
        price_change.setTabOrder(self.confirm, self.cancel)

    def retranslateUi(self, price_change):
        _translate = QtCore.QCoreApplication.translate
        self.client_name.setText(_translate("price_change", "<html><head/><body><p><span style=\" font-size:28pt; font-style:italic;\">BMT</span></p></body></html>"))
        self.cancel.setText(_translate("price_change", "取消"))
        self.confirm.setText(_translate("price_change", "修改售价"))
        self.label.setText(_translate("price_change", "售价更新"))
        self.label_3.setText(_translate("price_change", "书籍名称"))
        self.label_4.setText(_translate("price_change", "售价"))
        self.original_price.setText(_translate("price_change", "当前售价"))
        self.label_5.setText(_translate("price_change", "书籍类型"))
        self.client_logo.setText(_translate("price_change", "<html><head/><body><p><img src=\":/logo/resource/BMT_128.ico\"/></p></body></html>"))

import resource_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    price_change = QtWidgets.QMainWindow()
    ui = Ui_price_change()
    ui.setupUi(price_change)
    price_change.show()
    sys.exit(app.exec_())

